from typing import Protocol
from ytmusicapi import YTMusic
from yt_playlist.config import IdentityConfig

class IdentityClient(Protocol):
    def get_library_playlists(self, limit: int = ...) -> list: ...
    def get_playlist(self, playlistId: str, limit: int = ...) -> dict: ...
    def get_history(self) -> list: ...
    def create_playlist(self, title: str, description: str) -> str: ...
    def add_playlist_items(self, playlistId: str, videoIds: list) -> None: ...
    def remove_playlist_items(self, playlistId: str, videos: list) -> None: ...
    def delete_playlist(self, playlistId: str) -> None: ...
    def search(self, query: str, filter: str = ...) -> list: ...

def build_client(cfg: IdentityConfig, auth_blob: str) -> YTMusic:
    # auth_blob is the captured browser/oauth auth; brand_account_id selects the identity
    return YTMusic(auth_blob, cfg.brand_account_id)
